### ISSUE TITLE
Add "Document your script API" guideline?

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/npm-style-guide#13]
In the RiotJS Style Guide we have a rule "[Document your tag API](https://github.com/voorhoede/riotjs-style-guide#document-your-tag-api)". I think it makes sense to do the same for your npm scripts as they are the "facade API of all your scripts", make your scripts accessible, don't require devs to dive into your package.json or individual npm module docs (and we can probably find more reasons :) ).

Format:

``` markdown
`npm run ...` | Description
---|---
task | What it does as a plain human readable description.
```

Example (borrowed from [RiotJS Demos > Contribution guidelines > Scripts](https://github.com/voorhoede/riotjs-demos/blob/master/CONTRIBUTING.md#scripts)):

``` markdown
`npm run ...` | Description
---|---
`build` | Compile, bundle and minify all tag files.
`build:tags` | Compile and bundle all tag files to `dist/tags.js`.
`build:min` | Minify tags bundle to `dist/tags.min.js` plus sourcemap.
`commit` | Prompts you to fill out your git commit message step-by-step.
`start` | Starts a server on `http://localhost:33667` ("demos" in T9).
`test` | Run linter.
`test:eslint` | Check all tag files for format and syntax errors.
```

Result:

| `npm run ...` | Description |
| --- | --- |
| `build` | Compile, bundle and minify all tag files. |
| `build:tags` | Compile and bundle all tag files to `dist/tags.js`. |
| `build:min` | Minify tags bundle to `dist/tags.min.js` plus sourcemap. |
| `commit` | Prompts you to fill out your git commit message step-by-step. |
| `start` | Starts a server on `http://localhost:33667` ("demos" in T9). |
| `test` | Run linter. |
| `test:eslint` | Check all tag files for format and syntax errors. |

Notes:
- alphabetise?
- exclude pre- & post- scripts.

**Comment by jpsc** [comment]
This is good. It's the only way to document npm script tasks that only rely on cli versions of modules.
Alphabetise I don't think. Should be grouped by task relationship. (like you have on your example). And yes think it should exclude the pre and post scripts.
