### ISSUE TITLE
specify engines on package.json ?

### ISSUE THREAD

**Issue by jpsc** [voorhoede/npm-style-guide#4]
- it will throw a warning if the user does not match the required version of `node` or `npm`
- it's just a warning user can still use it at his decision

Adding this to package.json

``` javascript
"engines" : { 
  "node" : "5.10.0",
  "npm" : "3.8.5"
}

```

**Comment by jbmoelker** [comment]
We can use [Facebook's fbjs > node > check-dev-engines.js](https://github.com/facebook/fbjs/blob/master/scripts/node/check-dev-engines.js) to check if current engines meet those required by the project.

You can use it on `postinstall` (needs to install `semver` first) to check the dev engines (like [React does](https://github.com/facebook/react/blob/caa78f/package.json#L72)):

``` json
{
  "postinstall": "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"
}
```

We might even consider turning this into a separate npm module, so you can simply do `check-dev-engines package.json`. Maybe something for @Siilwyn?

**Comment by jbmoelker** [comment]
I'd also link to the [npm guide > engines section](https://docs.npmjs.com/files/package.json#engines)

And I'd add that the `engines` settings are "advisory only" as [`engineStrict` is deprecated with npm 3.0.0](https://docs.npmjs.com/files/package.json#enginestrict):

> "Note that, unless the user has set the engine-strict config flag, this field is advisory only."
> "This feature [engine-strict] was deprecated with npm 3.0.0"

However by adding the `check-dev-engines` script we can again force strict engines.

**Comment by jpsc** [comment]
Shouldn't this be on preinstall?

Based on npm scripts [best practices](https://docs.npmjs.com/misc/scripts#best-practices) we should not use preinstall but isn't this the non-rule ?

**Comment by Siilwyn** [comment]
Like [this one](https://libraries.io/npm/check-pkg-engines)? @jbmoelker

**Comment by jbmoelker** [comment]
@jpsc the check uses the semver module, so needs to install at least that one first. I assume that's why React uses `postinstall` as well.

**Comment by jbmoelker** [comment]
@Siilwyn yup, looks good. The FB one is used a lot. I don't really have a preference. Just that we need such a script in our toolbox. But at least we don't have to write the module ourselves :)

**Comment by jpsc** [comment]
I think we should not include that check. One of the pro's that I stated on the initial issue is that, this only throws an warning. With that package it does nothing if you don't have the right version.

**Comment by jbmoelker** [comment]
@jpsc I guess I mainly find it mainly important that we check:
- npm ^3 because of flat dependency structure (think Windows)
- ES6 support depends on exact Node version, so by exactly configuring that one, you can use specific ES6 features without a problem.
