### ISSUE TITLE
prefix tasks to bundle them

### ISSUE THREAD

**Issue by jpsc** [voorhoede/npm-style-guide#6]
- adding a prefix like `task:..` helps bundling for a specific task
- you can use `npm-run-all task:*` and all related tasks will run (specially important if add more tasks later there is no need for changing)

**Comment by petergoes** [comment]
how would you write that down? Something like this?

``` js
...
    scripts: {
         tasks: {
            build : '',
            serve: ''
        }
    }
...
```

**Comment by jpsc** [comment]
``` javascript
scripts: {
  "build:js": "browserify",
  "build:css": "postcss -u"
}
```

**Comment by jbmoelker** [comment]
I'd put this guideline directly after "[Write atomic tasks](https://github.com/voorhoede/npm-style-guide#write-atomic-tasks)" and try to use the same example so that it makes most sense to the reader.
